/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.RecipeController;
import Model.Recipe;
import java.util.List;

public class AllRecipesPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    public AllRecipesPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();   // MUST be here
        loadRecipes();
    }

    private void loadRecipes() {
        List<Recipe> recipes = RecipeController.getAllRecipes();
        System.out.println("Total recipes loaded: " + recipes.size());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void initComponents() {

        javax.swing.JLabel title = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        title.setText("ALL RECIPES");
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setFont(new java.awt.Font("Segoe UI", 1, 24));

        add(title, java.awt.BorderLayout.NORTH);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

