/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
 import Controller.RecipeController;

import java.awt.CardLayout;

/**
 *
 * @author ACER
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    private CardLayout cardLayout;
    
    private LoginPanel loginPanel;
    private AdminDashboardPanel adminDashboardPanel;
    private UserDashboardPanel userDashboardPanel;
    private RecipeListPanel recipeListPanelAdmin;
    private RecipeListPanel recipeListPanelUser;

    private RecipeFormPanel recipeFormPanel;
    private MealPlannerPanel mealPlannerPanel;
    private ShoppingListPanel shoppingListPanel;
    private SignUpPanel signUpPanel;
    
    
    
    public MainFrame() {
        initComponents();
        RecipeController.loadSampleData();


        //creating cardlayout 
        cardLayout=new CardLayout();
        getContentPane().setLayout(cardLayout);
        
        //creating panel ones
        loginPanel = new LoginPanel(this);
        adminDashboardPanel = new AdminDashboardPanel(this);
        userDashboardPanel = new UserDashboardPanel(this);
        recipeListPanelAdmin = new RecipeListPanel(this, true);
        recipeListPanelUser  = new RecipeListPanel(this, false);
        recipeFormPanel = new RecipeFormPanel(this);
        mealPlannerPanel = new MealPlannerPanel(this);
        shoppingListPanel = new ShoppingListPanel(this);
        signUpPanel = new SignUpPanel(this);
        
        
        //adding panels
        getContentPane().add(loginPanel, "LOGIN");
        getContentPane().add(adminDashboardPanel, "ADMIN");
        getContentPane().add(userDashboardPanel, "USER");

        getContentPane().add(recipeListPanelAdmin, "RECIPES_ADMIN");
        getContentPane().add(recipeListPanelUser, "RECIPES_USER");

        getContentPane().add(recipeFormPanel, "RECIPE_FORM");
        getContentPane().add(mealPlannerPanel, "MEAL_PLANNER");
        getContentPane().add(shoppingListPanel, "SHOPPING_LIST");
        getContentPane().add(signUpPanel, "SIGNUP");

        


        
        //show first screen
        showScreen("LOGIN");
        
        // FRAME SETTINGS
        setTitle("MealMate");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
       
    
    }
        //adding method
      public void showScreen(String screenName) {

    // ===== Recipe Lists =====
    if (screenName.equals("RECIPES_ADMIN")) {
        recipeListPanelAdmin.loadRecipes();
    }

    if (screenName.equals("RECIPES_USER")) {
        recipeListPanelUser.loadRecipes();
    }

    // ===== Recipe Form =====
    if (screenName.equals("RECIPE_FORM")) {
        recipeFormPanel.clearForm();
    }

    // ===== Meal Planner (Admin) =====
    if (screenName.equals("MEAL_PLANNER_ADMIN")) {
        mealPlannerPanel.setAdminView(true);
        cardLayout.show(getContentPane(), "MEAL_PLANNER");
        return;
    }

    // ===== Meal Planner (User) =====
    if (screenName.equals("MEAL_PLANNER_USER")) {
        mealPlannerPanel.setAdminView(false);
        cardLayout.show(getContentPane(), "MEAL_PLANNER");
        return;
    }

    // ===== Default Navigation =====
    cardLayout.show(getContentPane(), screenName);
}



    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
